# Project: L2Q7
# Makefile created by Dev-C++ 5.6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = l2q7.o
LINKOBJ  = l2q7.o
LIBS     = -L"C:/Users/D3XT3R/Downloads/Dev-Cpp/MinGW32/lib" -L"C:/Users/D3XT3R/Downloads/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc
INCS     = -I"C:/Users/D3XT3R/Downloads/Dev-Cpp/MinGW32/include" -I"C:/Users/D3XT3R/Downloads/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/D3XT3R/Downloads/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/D3XT3R/Downloads/Dev-Cpp/MinGW32/include" -I"C:/Users/D3XT3R/Downloads/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/D3XT3R/Downloads/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Users/D3XT3R/Downloads/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = L2Q7.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

l2q7.o: l2q7.c
	$(CC) -c l2q7.c -o l2q7.o $(CFLAGS)
